# Generated by Django 3.1.7 on 2021-04-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='Snikers',
        ),
    ]
