# Generated by Django 3.1.7 on 2021-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210405_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snikers',
            options={'verbose_name': 'sniker', 'verbose_name_plural': 'snikers'},
        ),
        migrations.RemoveField(
            model_name='snikers',
            name='name',
        ),
        migrations.AddField(
            model_name='snikers',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snikers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snikers',
            name='form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snikers',
            name='size',
            field=models.CharField(choices=[('45', '45 EU'), ('46', '46 EU'), ('47', '47 EU'), ('48', '48 EU')], max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
        migrations.AlterModelTable(
            name='snikers',
            table='snikers',
        ),
    ]
