# Generated by Django 3.1.7 on 2021-04-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210411_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snikers',
            old_name='form',
            new_name='model',
        ),
    ]
