# Generated by Django 3.1.7 on 2021-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210411_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snikers',
            name='company',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snikers',
            name='model',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
